# ============================================================================
# SuperLite OS — Yocto Layer Configuration
# Layer: meta-superlite
# ============================================================================

# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# Let BitBake know where to find recipe files
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-superlite"
BBFILE_PATTERN_meta-superlite = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-superlite = "10"

# Layer dependencies
LAYERDEPENDS_meta-superlite = "core openembedded-layer wayland-layer meta-alpine"
LAYERSERIES_COMPAT_meta-superlite = "scarthgap styhead"

# This layer provides distro, machine, and image recipes
HOSTTOOLS += "mksquashfs xorriso mcopy mkfs.vfat"
