#
# foot config
#
# -*- conf -*-

locked-title=no

font=xos4 Terminus:size=8

initial-window-size-pixels=498x252
pad=6x6

include=~/.config/foot/monokai-stone

[bell]

[scrollback]

[url]

[cursor]
style=underline
color=6F44F0 ffffff
blink=yes

[mouse]
hide-when-typing=yes

[colors-dark]
#alpha=1.0

[csd]

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
font-increase=Control+plus Control+equal Control+KP_Add
font-reset=Control+0 Control+KP_0

[search-bindings]

[url-bindings]

[mouse-bindings]

[tweak]
font-monospace-warn=no
