# SuperLite OS — Foot Terminal Config

font=xos4 Terminus:size=8
initial-window-size-pixels=498x252
pad=6x6
locked-title=no

[scrollback]
lines=1000

[cursor]
style=underline
blink=yes

[mouse]
hide-when-typing=yes

[colors]
# Monokai Stone inspired
alpha=1.0
foreground=000000
background=fffff8
selection-foreground=ffffff
selection-background=a4a4a4

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
font-increase=Control+plus Control+equal Control+KP_Add
font-reset=Control+0 Control+KP_0
