# SuperLite OS — Foot terminal (LabWC-Alpine-Netbook style)
# Monokai Stone color scheme

[main]
term=foot
font=xos4 Terminus:size=8
pad=6x6
initial-window-size-chars=120x35
locked-title=no

[cursor]
style=underline
blink=yes

[mouse]
hide-when-typing=yes

[colors]
alpha=1.0
background=3b224c
foreground=a4a0e8
regular0=403E41
regular1=FF6188
regular2=A9DC76
regular3=FFD866
regular4=FC9867
regular5=AB9DF2
regular6=78DCE8
regular7=FCFCFA
bright0=727072
bright1=FF6188
bright2=A9DC76
bright3=FFD866
bright4=FC9867
bright5=AB9DF2
bright6=78DCE8
bright7=FCFCFA

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
font-increase=Control+plus Control+equal Control+KP_Add
font-reset=Control+0 Control+KP_0
